apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: hello-arc-config
    files:
      - values.yaml=my-values.yaml