apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-arc
  namespace: prod
spec:
  interval: 30s
  releaseName: hello-arc
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: GitRepository
        name: hello-arc
  valuesFrom:
    - kind: ConfigMap
      name: hello-arc-config